service: serverless

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1
  stage: dev

plugins:
  - serverless-offline

functions:
  api:
    handler: src/api/api.handler
    events:
      - http:
          path: /api
          method: GET
          cors: true
  todos:
    handler: src/api/todos.handler
    events:
      - http:
          path: /todos
          method: GET
          cors: true

  todo:
    handler: src/api/todo.handler
    events:
      - http:
          path: todo/{id}
          method: get
          cors: true
